name: Cowsay CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build_and_package_application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        # Allow the runner to check out the source code from the repository.

      - name: Build Docker image
        run: docker build -t cowsay-app:latest .

      - name: Run Docker container
        run: docker run -d -p 8080:8080 cowsay-app:latest

      - name: Check application
        run: sleep 5

      - name: Check application
        run: curl http://localhost:8080

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # Authenticates Docker to GHCR using GitHub's built-in token.

      - name: Tag Docker image
        run: docker tag cowsay-app:latest ghcr.io/riki-dev-1/cowsay-app:latest
        # Tags the Docker image for GHCR. Note the format: ghcr.io/username/repository:tag

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/riki-dev-1/cowsay-app:latest
        # Pushes the Docker image to GitHub Container Registry.
